const $=s=>document.querySelector(s),API=FB.url+"/functions/v1/admin-api";let DATA=null;
function session(){let access_token=localStorage.getItem("fb_access_token"),refresh_token=localStorage.getItem("fb_refresh_token");return access_token?{access_token,refresh_token}:null}
async function call(method="GET",body){let s=session();if(!s?.access_token){location="admin-login.html";throw Error("Sessão administrativa não encontrada.")}let r=await fetch(API,{method,headers:{apikey:FB.key,Authorization:"Bearer "+s.access_token,"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});if(r.status===401){try{s=await fbSession.refresh()}catch(e){fbSession.clear();location="admin-login.html";throw e}if(s?.access_token)return call(method,body)}let raw=await r.text(),j={};try{j=raw?JSON.parse(raw):{}}catch{throw Error("Resposta inválida do servidor.")}if(!r.ok)throw Error(j.error||j.message||("Erro "+r.status));return j}
const esc=x=>String(x||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function license(uid){return(DATA.licenses||[]).find(x=>x.user_id===uid)}function device(id){return(DATA.devices||[]).find(x=>x.license_id===id)}
function remaining(l){if(!l)return"SEM ACESSO";if(l.status==="blocked")return"BLOQUEADO";if(l.plan_id==="lifetime"&&!l.expires_at)return"VITALÍCIO";if(!l.expires_at)return"SEM VENCIMENTO";let ms=new Date(l.expires_at)-Date.now();if(ms<=0)return"VENCIDO";let d=Math.floor(ms/86400000),h=Math.floor(ms%86400000/3600000),m=Math.floor(ms%3600000/60000);return d?d+"d "+h+"h "+m+"min":h+"h "+m+"min"}
function money(v){return "R$ "+Number(v||0).toFixed(2).replace(".",",")}function renderPrices(){let m=(DATA.plans||[]).find(p=>p.id==="monthly"),l=(DATA.plans||[]).find(p=>p.id==="lifetime");if(m){$("#mMonthly").textContent=money(m.price);$("#priceMonthly").value=Number(m.price).toFixed(2)}if(l){$("#mLifetime").textContent=money(l.price);$("#priceLifetime").value=Number(l.price).toFixed(2)}}
function isActive(l){return !!l&&l.status==="active"&&(!l.expires_at||new Date(l.expires_at)>new Date())}
function isLifetime(l){return !!l&&l.plan_id==="lifetime"&&!l.expires_at&&l.status!=="blocked"}
function isMonthly(l){return !!l&&l.plan_id==="monthly"&&l.status!=="blocked"}
function isTemporary(l){return !!l&&!!l.expires_at&&l.plan_id!=="monthly"&&l.status!=="blocked"&&new Date(l.expires_at)>new Date()}
function isBlocked(l){return !l||l.status==="blocked"||(l.expires_at&&new Date(l.expires_at)<=new Date())}
function renderMetrics(){const ls=DATA.licenses||[],active=ls.filter(isActive).length,lifetime=ls.filter(isLifetime).length,monthly=ls.filter(isMonthly).length,trial=ls.filter(isTemporary).length,blocked=(DATA.users||[]).filter(u=>isBlocked(license(u.id))).length;$("#mUsers").textContent=(DATA.users||[]).length;$("#mActive").textContent=active;$("#mLifetimeClients").textContent=lifetime;$("#mMonthlyClients").textContent=monthly;$("#mTrial").textContent=trial;$("#mBlocked").textContent=blocked;$("#sActive").textContent=active;$("#sLifetime").textContent=lifetime;$("#sMonthly").textContent=monthly;$("#sTrial").textContent=trial}
function matchesFilter(l,f){if(f==="all")return true;if(f==="active")return isActive(l);if(f==="lifetime")return isLifetime(l);if(f==="monthly")return isMonthly(l);if(f==="temporary")return isTemporary(l);if(f==="blocked")return isBlocked(l);return true}
function render(){renderPrices();renderMetrics();let q=$("#search").value.toLowerCase(),f=$("#statusFilter")?.value||"all",users=DATA.users.filter(u=>(u.email||"").toLowerCase().includes(q)&&matchesFilter(license(u.id),f));$("#rows").innerHTML=users.length?users.map(u=>{let l=license(u.id),d=l&&device(l.id);const state=isLifetime(l)?"lifetime":isMonthly(l)?"monthly":isTemporary(l)?"temporary":isActive(l)?"active":"inactive";const label=isLifetime(l)?"VITALÍCIO":isMonthly(l)?"MENSAL":isTemporary(l)?"TEMPORÁRIO":isActive(l)?"ATIVO":(l?.status==="blocked"?"BLOQUEADO":remaining(l)==="VENCIDO"?"VENCIDO":"SEM ACESSO");return '<tr class="client-row"><td><div class="client-identity"><div><b>'+esc(u.email)+'</b><small>Cliente cadastrado</small></div></div></td><td><div class="licenseStatus">'+remaining(l)+'</div><small>'+(l?.expires_at?"Vence: "+new Date(l.expires_at).toLocaleString("pt-BR"):"Sem data de vencimento")+'</small></td><td><span class="status-chip '+state+'">'+label+'</span></td><td><div class="device-cell"><b>'+esc(d?.device_name||"Nenhum")+'</b><small>'+(d?"PC vinculado":"Sem dispositivo vinculado")+'</small></div></td><td><div class="accessEditor"><input type="number" min="1" step="1" value="24" data-time="'+u.id+'"><select data-unit="'+u.id+'"><option value="hours">Horas</option><option value="days">Dias</option></select><button class="btn mini" data-action="set_time" data-user="'+u.id+'">DEFINIR TEMPO</button><button class="btn mini" data-action="lifetime" data-user="'+u.id+'">Vitalício</button></div><div class="adminActions">'+(l?'<button class="ghost mini" data-action="'+(l.status==="blocked"?"unblock":"block")+'" data-license="'+l.id+'">'+(l.status==="blocked"?"Desbloquear":"Bloquear")+'</button> <button class="ghost mini" data-action="release" data-license="'+l.id+'">Liberar PC</button> <button class="ghost mini" data-action="remove_access" data-user="'+u.id+'">Remover acesso</button> ':'')+'<button class="ghost mini" data-action="delete_user" data-user="'+u.id+'">Excluir usuário</button></div></td></tr>'}).join(""):'<tr><td colspan="5" class="empty">Nenhum cliente encontrado.</td></tr>'}
async function act(b){let action=b.dataset.action,userId=b.dataset.user||null,licenseId=b.dataset.license||null,body={action,userId,licenseId};if(action==="set_time"){let input=document.querySelector('[data-time="'+userId+'"]'),unit=document.querySelector('[data-unit="'+userId+'"]');body.amount=Number(input.value);body.unit=unit.value;if(!body.amount||body.amount<1)return alert("Informe a quantidade de horas ou dias.")}if(!confirm(action==="set_time"?"Definir exatamente este tempo a partir de agora?":"Confirmar esta ação?"))return;try{$("#msg").textContent="Salvando alteração...";await call("POST",body);await load();$("#msg").textContent="Alteração salva com sucesso."}catch(e){$("#msg").textContent="Erro: "+e.message}}
$("#rows").addEventListener("click",e=>{let b=e.target.closest("button[data-action]");if(b)act(b)});async function load(){try{$("#msg").textContent="Carregando clientes...";DATA=await call();DATA=DATA||{};DATA.users=Array.isArray(DATA.users)?DATA.users:[];DATA.licenses=Array.isArray(DATA.licenses)?DATA.licenses:[];DATA.devices=Array.isArray(DATA.devices)?DATA.devices:[];DATA.plans=Array.isArray(DATA.plans)?DATA.plans:[];render();$("#msg").textContent="Painel administrativo conectado • "+DATA.users.length+" cliente(s)."}catch(e){console.error("Admin load",e);$("#msg").textContent="Erro ao carregar clientes: "+e.message;let rows=$("#rows");if(rows)rows.innerHTML='<tr><td colspan="5" class="empty">ERRO: '+esc(e.message)+' — faça login novamente se a sessão expirou.</td></tr>'}}$("#search").addEventListener("input",()=>DATA&&render());let sf=$("#statusFilter");if(sf)sf.addEventListener("change",()=>DATA&&render());$("#logout").onclick=()=>{fbSession.clear();location="admin-login.html"};load();setInterval(()=>DATA&&render(),60000);
$("#savePrices").onclick=async()=>{let monthly=Number($("#priceMonthly").value),lifetime=Number($("#priceLifetime").value);if(monthly<=0||lifetime<=0)return alert("Informe os dois valores.");if(!confirm("Salvar estes preços na página de vendas?"))return;try{$("#msg").textContent="Salvando preços...";await call("POST",{action:"set_prices",monthly,lifetime});await load();$("#msg").textContent="Preços atualizados no site."}catch(e){$("#msg").textContent="Erro: "+e.message}};


async function loadDownloadManager(){try{const d=await call(),box=$("#adminVersionList"),list=Array.isArray(d.downloads)?d.downloads:[];box.innerHTML=list.length?list.map(v=>'<article class="admin-version-item"><div><b>V'+esc(v.version)+'</b><span>'+esc(v.release_date||"")+' • '+esc(v.note||"")+'</span></div><span class="status-chip '+(v.is_current?"active":"inactive")+'">'+(v.is_current?"ATUAL":"ANTERIOR")+'</span></article>').join(""):'<article class="admin-version-item"><div><b>Nenhuma versão publicada</b></div></article>'}catch(e){$("#releaseHelp").textContent="Não foi possível carregar o histórico de versões."}}
$("#prepareRelease").onclick=async()=>{const b=$("#prepareRelease"),v=$("#releaseVersion").value.trim(),date=$("#releaseDate").value.trim(),url=$("#releaseUrl").value.trim(),note=$("#releaseNote").value.trim();if(!v||!url)return alert("Informe a versão e o link do instalador.");if(!confirm("Publicar a versão V"+v+" como versão atual para download?"))return;try{b.disabled=true;b.textContent="PUBLICANDO...";$("#releaseHelp").textContent="Publicando versão...";await call("POST",{action:"publish_release",version:v,date,url,note});await loadDownloadManager();$("#releaseHelp").innerHTML="<b>Versão V"+esc(v)+" publicada com sucesso.</b> Ela já está definida como versão atual para download. Clientes, licenças e dispositivos não foram alterados."}catch(e){$("#releaseHelp").textContent="Erro ao publicar: "+e.message}finally{b.disabled=false;b.textContent="PUBLICAR VERSÃO"}};
loadDownloadManager();

// Tutorial único: salva no Supabase e substitui o anterior
async function loadTutorialAdmin(){const box=$("#tutorialAdminList");if(!box)return;try{const d=await call(),list=Array.isArray(d.tutorials)?d.tutorials:[];box.innerHTML=list.length?list.slice(0,1).map(t=>'<article class="tutorial-admin-card"><div><small>VÍDEO ATUAL</small><b>'+esc(t.title||"Tutorial FIRE BLAZE")+'</b><span>'+esc(t.description||"")+'</span></div><div class="tutorial-card-actions"><span class="status-chip active">PUBLICADO</span><button class="ghost mini" data-remove-tutorial="'+esc(t.id)+'">REMOVER VÍDEO</button></div></article>').join(""):'<article class="tutorial-admin-empty">Nenhum vídeo publicado ainda.</article>'}catch(e){box.innerHTML='<article class="tutorial-admin-empty">Não foi possível carregar o vídeo.</article>'}}
$("#tutorialAdminList")?.addEventListener("click",async e=>{const b=e.target.closest("button[data-remove-tutorial]");if(!b)return;if(!confirm("Remover este vídeo da área do cliente?"))return;const msg=$("#tutorialAdminMsg");try{b.disabled=true;b.textContent="REMOVENDO...";await call("POST",{action:"delete_tutorial",id:b.dataset.removeTutorial});msg.innerHTML="<b>Vídeo removido.</b> Ele não aparece mais na área do cliente.";await loadTutorialAdmin()}catch(err){msg.textContent="Erro ao remover: "+err.message}});
const tutorialAdd=$("#tutorialAdminAdd");if(tutorialAdd)tutorialAdd.onclick=async()=>{const title=$("#tutorialAdminTitle").value.trim(),url=$("#tutorialAdminUrl").value.trim(),description=$("#tutorialAdminDescription").value.trim(),msg=$("#tutorialAdminMsg");if(!title||!url)return alert("Informe o título e o link do YouTube.");if(!/(youtu\.be\/|youtube\.com\/)/i.test(url))return alert("Cole um link válido do YouTube.");try{tutorialAdd.disabled=true;tutorialAdd.textContent="PUBLICANDO...";await call("POST",{action:"add_tutorial",title,youtube_url:url,description});msg.innerHTML="<b>Vídeo publicado com sucesso.</b> Ele já aparece dentro da área do cliente.";await loadTutorialAdmin()}catch(e){msg.textContent="Erro ao publicar: "+e.message}finally{tutorialAdd.disabled=false;tutorialAdd.textContent="PUBLICAR VÍDEO"}};loadTutorialAdmin();
