const $=s=>document.querySelector(s), API=FB.url+"/functions/v1/admin-api"; let DATA=null;
function session(){const access_token=localStorage.getItem("fb_access_token"),refresh_token=localStorage.getItem("fb_refresh_token");return access_token?{access_token,refresh_token}:null}
async function call(method="GET",body){let s=session();if(!s?.access_token){location="login.html";return}let r=await fetch(API,{method,headers:{apikey:FB.key,Authorization:"Bearer "+s.access_token,"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});if(r.status===401){s=await fbSession.refresh();if(s)return call(method,body)}if(r.status===403){$("#msg").textContent="Acesso negado: esta conta não é administradora.";throw 0}let j=await r.json();if(!r.ok)throw Error(j.error||"Erro");return j}
function license(uid){return (DATA.licenses||[]).find(x=>x.user_id===uid)}
function device(lid){return (DATA.devices||[]).find(x=>x.license_id===lid)}
function esc(x){return String(x||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function planName(id){return id==="lifetime"?"Permanente":id==="trial"?"Teste 24h":id==="monthly"?"Mensal":id==="custom"?"Personalizado":id||"Sem licença"}
function expiry(l){if(!l)return "—";if(l.plan_id==="lifetime"&&!l.expires_at)return "Vitalício";return l.expires_at?new Date(l.expires_at).toLocaleString("pt-BR"):"—"}
function render(){let q=$("#search").value.toLowerCase(),users=DATA.users.filter(u=>(u.email||"").toLowerCase().includes(q));$("#mUsers").textContent=DATA.users.length;$("#mActive").textContent=DATA.licenses.filter(l=>l.status==="active"&&(!l.expires_at||new Date(l.expires_at)>new Date())).length;$("#rows").innerHTML=users.map(u=>{let l=license(u.id),d=l&&device(l.id),plan=l?planName(l.plan_id):"Sem licença",st=l?l.status:"—";let a='<button class="btn mini" data-action="grant" data-user="'+u.id+'" data-plan="trial">24h</button> <button class="btn mini" data-action="grant" data-user="'+u.id+'" data-plan="monthly">30 dias</button> <button class="btn mini" data-action="grant" data-user="'+u.id+'" data-plan="lifetime">Vitalício</button> <button class="btn mini" data-action="custom" data-user="'+u.id+'">Personalizado</button>';if(l)a+=' <button class="ghost mini" data-action="add_time" data-license="'+l.id+'">+ Tempo</button> <button class="ghost mini" data-action="'+(l.status==="blocked"?"unblock":"block")+'" data-license="'+l.id+'">'+(l.status==="blocked"?"Desbloquear":"Bloquear")+'</button> <button class="ghost mini" data-action="release" data-license="'+l.id+'">Liberar PC</button> <button class="ghost mini" data-action="remove_access" data-user="'+u.id+'">Remover acesso</button>';a+=' <button class="ghost mini" data-action="delete_user" data-user="'+u.id+'">Excluir usuário</button>';return '<tr><td><b>'+esc(u.email)+'</b></td><td>'+esc(plan)+'<br><small>'+esc(expiry(l))+'</small></td><td>'+esc(st)+'</td><td>'+esc(d?.device_name||"Nenhum")+'</td><td>'+a+'</td></tr>'}).join("")||'<tr><td colspan="5" class="empty">Nenhum cliente encontrado.</td></tr>'}
async function act(action,userId,licenseId,plan){let body={action,userId,licenseId,plan};if(action==="custom"||action==="add_time"){let amount=prompt("Quantidade (ex.: 2, 24, 30):");if(amount===null)return;let unit=prompt("Digite HORAS ou DIAS:","dias");if(unit===null)return;unit=unit.toLowerCase().startsWith("h")?"hours":"days";body={action:action==="custom"?"grant":"add_time",userId,licenseId,plan:"custom",amount:Number(amount),unit}}let msg=action==="delete_user"?"ATENÇÃO: excluir definitivamente este usuário?":"Confirmar esta ação?";if(!confirm(msg))return;try{$("#msg").textContent="Aplicando alteração...";await call("POST",body);await load()}catch(e){if(e)$("#msg").textContent="Erro: "+e.message}}
$("#rows").addEventListener("click",e=>{const b=e.target.closest("button[data-action]");if(b)act(b.dataset.action,b.dataset.user||null,b.dataset.license||null,b.dataset.plan||null)});
async function load(){try{DATA=await call();$("#msg").textContent="Painel administrativo conectado com segurança.";render()}catch(e){if(e)$("#msg").textContent="Erro: "+e.message}}
$("#search").addEventListener("input",()=>DATA&&render());$("#logout").onclick=()=>{fbSession.clear();location="login.html"};load();