const $=s=>document.querySelector(s),API=FB.url+"/functions/v1/admin-api";let DATA=null;
function session(){let access_token=localStorage.getItem("fb_access_token"),refresh_token=localStorage.getItem("fb_refresh_token");return access_token?{access_token,refresh_token}:null}
async function call(method="GET",body){let s=session();if(!s?.access_token){location="admin-login.html";return}let r=await fetch(API,{method,headers:{apikey:FB.key,Authorization:"Bearer "+s.access_token,"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});if(r.status===401){s=await fbSession.refresh();if(s)return call(method,body)}let j=await r.json();if(!r.ok)throw Error(j.error||"Erro");return j}
const esc=x=>String(x||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function license(uid){return(DATA.licenses||[]).find(x=>x.user_id===uid)}function device(id){return(DATA.devices||[]).find(x=>x.license_id===id)}
function isActive(l){return !!l&&l.status==="active"&&(!l.expires_at||new Date(l.expires_at)>new Date())}
function isLifetime(l){return !!l&&l.plan_id==="lifetime"&&!l.expires_at&&l.status!=="blocked"}
function isMonthly(l){return !!l&&l.plan_id==="monthly"&&l.status!=="blocked"}
function isTemporary(l){return !!l&&!!l.expires_at&&l.plan_id!=="monthly"&&l.status!=="blocked"&&new Date(l.expires_at)>new Date()}
function isBlocked(l){return !l||l.status==="blocked"||(l.expires_at&&new Date(l.expires_at)<=new Date())}
function remaining(l){if(!l)return"SEM ACESSO";if(l.status==="blocked")return"BLOQUEADO";if(l.plan_id==="lifetime"&&!l.expires_at)return"VITALÍCIO";if(!l.expires_at)return"SEM VENCIMENTO";let ms=new Date(l.expires_at)-Date.now();if(ms<=0)return"VENCIDO";let d=Math.floor(ms/86400000),h=Math.floor(ms%86400000/3600000),m=Math.floor(ms%3600000/60000);return d?d+"d "+h+"h "+m+"min":h+"h "+m+"min"}
function money(v){return "R$ "+Number(v||0).toFixed(2).replace(".",",")}
function renderPrices(){let m=(DATA.plans||[]).find(p=>p.id==="monthly"),l=(DATA.plans||[]).find(p=>p.id==="lifetime");if(m){$("#mMonthly").textContent=money(m.price);$("#priceMonthly").value=Number(m.price).toFixed(2)}if(l){$("#mLifetime").textContent=money(l.price);$("#priceLifetime").value=Number(l.price).toFixed(2)}}
function renderMetrics(){const ls=DATA.licenses||[],active=ls.filter(isActive).length,lifetime=ls.filter(isLifetime).length,monthly=ls.filter(isMonthly).length,trial=ls.filter(isTemporary).length,blocked=(DATA.users||[]).filter(u=>isBlocked(license(u.id))).length;$("#mUsers").textContent=(DATA.users||[]).length;$("#mActive").textContent=active;$("#mLifetimeClients").textContent=lifetime;$("#mMonthlyClients").textContent=monthly;$("#mTrial").textContent=trial;$("#mBlocked").textContent=blocked;$("#sActive").textContent=active;$("#sLifetime").textContent=lifetime;$("#sMonthly").textContent=monthly;$("#sTrial").textContent=trial}
function renderNotifications(){const box=$("#adminNotifications");if(!box)return;const ns=DATA.notifications||[];box.innerHTML=ns.length?ns.map(n=>'<article><div><strong>'+esc(n.title)+'</strong><span>'+new Date(n.created_at).toLocaleString("pt-BR")+'</span></div><p>'+esc(n.message)+'</p><button class="ghost mini" data-notification-delete="'+n.id+'">REMOVER</button></article>').join(""):""}
function matchesFilter(l,f){if(f==="all")return true;if(f==="active")return isActive(l);if(f==="lifetime")return isLifetime(l);if(f==="monthly")return isMonthly(l);if(f==="temporary")return isTemporary(l);if(f==="blocked")return isBlocked(l);return true}
function render(){renderPrices();renderMetrics();renderNotifications();let q=$("#search").value.toLowerCase(),f=$("#statusFilter")?.value||"all",users=DATA.users.filter(u=>(u.email||"").toLowerCase().includes(q)&&matchesFilter(license(u.id),f));$("#rows").innerHTML=users.length?users.map(u=>{let l=license(u.id),d=l&&device(l.id);let state=isLifetime(l)?"lifetime":isMonthly(l)?"monthly":isTemporary(l)?"temporary":isActive(l)?"active":"inactive",label=isLifetime(l)?"VITALÍCIO":isMonthly(l)?"MENSAL":isTemporary(l)?"TEMPORÁRIO":isActive(l)?"ATIVO":(l?.status==="blocked"?"BLOQUEADO":remaining(l)==="VENCIDO"?"VENCIDO":"SEM ACESSO");return '<tr class="client-row"><td><div class="client-identity"><span class="presence-dot pending" title="Status online será ativado na próxima versão do Mult"></span><div><b>'+esc(u.email)+'</b><small>Presença online: aguardando integração com o Mult</small></div></div></td><td><div class="licenseStatus">'+remaining(l)+'</div><small>'+(l?.expires_at?"Vence: "+new Date(l.expires_at).toLocaleString("pt-BR"):"Sem data de vencimento")+'</small></td><td><span class="status-chip '+state+'">'+label+'</span></td><td><div class="device-cell"><b>'+esc(d?.device_name||"Nenhum")+'</b><small>'+(d?"PC vinculado":"Sem dispositivo vinculado")+'</small></div></td><td><div class="accessEditor"><input type="number" min="1" step="1" value="24" data-time="'+u.id+'"><select data-unit="'+u.id+'"><option value="hours">Horas</option><option value="days">Dias</option></select><button class="btn mini" data-action="set_time" data-user="'+u.id+'">DEFINIR TEMPO</button><button class="btn mini" data-action="lifetime" data-user="'+u.id+'">Vitalício</button></div><div class="adminActions">'+(l?'<button class="ghost mini" data-action="'+(l.status==="blocked"?"unblock":"block")+'" data-license="'+l.id+'">'+(l.status==="blocked"?"Desbloquear":"Bloquear")+'</button> <button class="ghost mini" data-action="release" data-license="'+l.id+'">Liberar PC</button> <button class="ghost mini" data-action="remove_access" data-user="'+u.id+'">Remover acesso</button> ':'')+'<button class="ghost mini" data-action="delete_user" data-user="'+u.id+'">Excluir usuário</button></div></td></tr>'}).join(""):'<tr><td colspan="5" class="empty">Nenhum cliente encontrado.</td></tr>'}
async function act(b){let action=b.dataset.action,userId=b.dataset.user||null,licenseId=b.dataset.license||null,body={action,userId,licenseId};if(action==="set_time"){let input=document.querySelector('[data-time="'+userId+'"]'),unit=document.querySelector('[data-unit="'+userId+'"]');body.amount=Number(input.value);body.unit=unit.value;if(!body.amount||body.amount<1)return alert("Informe a quantidade de horas ou dias.")}if(!confirm(action==="set_time"?"Definir exatamente este tempo a partir de agora?":"Confirmar esta ação?"))return;try{$("#msg").textContent="Salvando alteração...";await call("POST",body);await load();$("#msg").textContent="Alteração salva com sucesso."}catch(e){$("#msg").textContent="Erro: "+e.message}}
$("#rows").addEventListener("click",e=>{let b=e.target.closest("button[data-action]");if(b)act(b)});
async function load(){try{DATA=await call();$("#msg").textContent="Painel atualizado • "+new Date().toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"});render()}catch(e){$("#msg").textContent="Erro: "+e.message}}
$("#search").addEventListener("input",()=>DATA&&render());$("#statusFilter").addEventListener("change",()=>DATA&&render());$("#logout").onclick=()=>{fbSession.clear();location="admin-login.html"};load();setInterval(()=>DATA&&render(),60000);
$("#savePrices").onclick=async()=>{let monthly=Number($("#priceMonthly").value),lifetime=Number($("#priceLifetime").value);if(monthly<=0||lifetime<=0)return alert("Informe os dois valores.");if(!confirm("Salvar estes preços na página de vendas?"))return;try{$("#msg").textContent="Salvando preços...";await call("POST",{action:"set_prices",monthly,lifetime});await load();$("#msg").textContent="Preços atualizados no site."}catch(e){$("#msg").textContent="Erro: "+e.message}};
$("#sendNotification").onclick=async()=>{const title=$("#notificationTitle").value.trim(),message=$("#notificationMessage").value.trim();if(!title||!message)return alert("Digite o título e a mensagem.");if(!confirm("Enviar esta notificação para todos os clientes?"))return;try{$("#msg").textContent="Enviando notificação...";await call("POST",{action:"send_notification",title,message});$("#notificationTitle").value="";$("#notificationMessage").value="";await load();$("#msg").textContent="Notificação enviada para os clientes."}catch(e){$("#msg").textContent="Erro: "+e.message}};
$("#adminNotifications").addEventListener("click",async e=>{const b=e.target.closest("[data-notification-delete]");if(!b||!confirm("Remover esta notificação da área dos clientes?"))return;try{await call("POST",{action:"delete_notification",id:Number(b.dataset.notificationDelete)});await load()}catch(err){$("#msg").textContent="Erro: "+err.message}});